version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t mewna/esp:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM .
    - run: docker push mewna/esp:$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM